// <auto-generated />
using System;
using Hv.Ppb302.DigitalThesis.WebClient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hv.Ppb302.DigitalThesis.WebClient.Migrations
{
    [DbContext(typeof(DigitalThesisDbContext))]
    partial class DigitalThesisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeoTagGroupTag", b =>
                {
                    b.Property<Guid>("GeoTagsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupTagsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GeoTagsId", "GroupTagsId");

                    b.HasIndex("GroupTagsId");

                    b.ToTable("GeoTagGroupTag");
                });

            modelBuilder.Entity("GroupTagMolarMosaic", b =>
                {
                    b.Property<Guid>("GroupTagsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MolarMosaicsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupTagsId", "MolarMosaicsId");

                    b.HasIndex("MolarMosaicsId");

                    b.ToTable("GroupTagMolarMosaic");
                });

            modelBuilder.Entity("GroupTagMolecularMosaic", b =>
                {
                    b.Property<Guid>("GroupTagsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MolecularMosaicsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GroupTagsId", "MolecularMosaicsId");

                    b.HasIndex("MolecularMosaicsId");

                    b.ToTable("GroupTagMolecularMosaic");
                });

            modelBuilder.Entity("Hv.Ppb302.DigitalThesis.WebClient.Models.GeoTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AudioFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasAudio")
                        .HasColumnType("bit");

                    b.Property<string>("PdfFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GeoTags");
                });

            modelBuilder.Entity("Hv.Ppb302.DigitalThesis.WebClient.Models.GroupTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GroupTags");
                });

            modelBuilder.Entity("Hv.Ppb302.DigitalThesis.WebClient.Models.MolarMosaic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AudioFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasAudio")
                        .HasColumnType("bit");

                    b.Property<string>("PdfFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MolarMosaics");
                });

            modelBuilder.Entity("Hv.Ppb302.DigitalThesis.WebClient.Models.MolecularMosaic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AudioFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasAudio")
                        .HasColumnType("bit");

                    b.Property<string>("PdfFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MolecularMosaics");
                });

            modelBuilder.Entity("GeoTagGroupTag", b =>
                {
                    b.HasOne("Hv.Ppb302.DigitalThesis.WebClient.Models.GeoTag", null)
                        .WithMany()
                        .HasForeignKey("GeoTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hv.Ppb302.DigitalThesis.WebClient.Models.GroupTag", null)
                        .WithMany()
                        .HasForeignKey("GroupTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupTagMolarMosaic", b =>
                {
                    b.HasOne("Hv.Ppb302.DigitalThesis.WebClient.Models.GroupTag", null)
                        .WithMany()
                        .HasForeignKey("GroupTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hv.Ppb302.DigitalThesis.WebClient.Models.MolarMosaic", null)
                        .WithMany()
                        .HasForeignKey("MolarMosaicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupTagMolecularMosaic", b =>
                {
                    b.HasOne("Hv.Ppb302.DigitalThesis.WebClient.Models.GroupTag", null)
                        .WithMany()
                        .HasForeignKey("GroupTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hv.Ppb302.DigitalThesis.WebClient.Models.MolecularMosaic", null)
                        .WithMany()
                        .HasForeignKey("MolecularMosaicsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
